/**
 * Injection tokens for dependency injection
 */
export const INJECTION_TOKENS = {
  AGENT_SECURE_STORAGE: Symbol('AGENT_SECURE_STORAGE'),
  WEBSOCKET_TRANSPORT: Symbol('WEBSOCKET_TRANSPORT'),
  VERIFIABLE_CREDENTIAL_SERVICE: Symbol('VERIFIABLE_CREDENTIAL_SERVICE'),
  AGENT_STORAGE: Symbol('AGENT_STORAGE'),
  VC_STORAGE: Symbol('VC_STORAGE'),
  WACI_PROTOCOL_STORAGE: Symbol('WACI_PROTOCOL_STORAGE'),
} as const;
